[build]
  command = "npm run build"
  publish = "dist"
  functions = "my_functions"

[build.environment]
  NODE_VERSION = "22.21.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-lighthouse"
